events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time';

    access_log /var/log/nginx/access.log main;

    upstream web {
        server web-app:8080;
    }

    upstream rec {
        server rec-service:8000;
    }

    server {
        listen 80;

        # API рекомендательного сервиса
        location /recommendations/ {
            proxy_pass http://rec;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /similar/ {
            proxy_pass http://rec;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://rec;
        }

        location /metrics {
            proxy_pass http://rec;
        }

        # Веб-интерфейс
        location / {
            proxy_pass http://web;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
